require 'bindata-contrib/version'
require 'bindata-contrib/bool'
require 'bindata-contrib/enum'
require 'bindata-contrib/flags'
require 'bindata-contrib/mac_address'
require 'bindata-contrib/ipv4_address'
require 'bindata-contrib/ipv6_address'
